build_from:
  amd64: mcr.microsoft.com/playwright/python:v1.49.1-jammy
  aarch64: mcr.microsoft.com/playwright/python:v1.49.1-jammy
  armv7: mcr.microsoft.com/playwright/python:v1.49.1-jammy
labels:
  org.opencontainers.image.title: "Agent Runner"
  org.opencontainers.image.description: "Home Assistant add-on for running AI/web agent jobs"
  org.opencontainers.image.source: "https://github.com/Sanher/sanher-ha-addons"
